type = "full_finetune"
name = "queue-e2e-test"
max_steps = 20
seq_len = 2048

[model]
name = "Qwen/Qwen3-30B-A3B-Instruct-2507"

[wandb]
project = "reverse-text"
name = "reverse-text"

[orchestrator]
batch_size = 128
group_size = 16

[orchestrator.train.sampling]
max_completion_tokens = 128

[[orchestrator.train.env]]
id = "jannikst/reverse-text"
name = "revtext"

[trainer.optim]
lr = 3e-6

[ckpt]

[inference]

[orchestrator.renderer]
name = "qwen3"
