## to run on 8H200
recompute_logprobs = false

[monitor.wandb]
project = "prime-rl-moe-debug" # TODO: Remove before merging

[model]
name = "Jackmin108/Moonlight-16B-A3B-Instruct-Fast"
ac = true
trust_remote_code = true

[optim]
lr = 1e-6 
