name_model = "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"
batch_size = 16
tp = "auto"
max_model_len = 24_000

[sampling]
n = 16

[len_reward]
reward_type = "exact"
length_prompt_location = "instruction"
target_lengths = [4000, 8000, 12000, 16000]