name_model = "Qwen32B"
max_samples = 32
batch_size = 32
#cpu_offload_gb = 300.0
#cpu_offload_percentage = 0.5
tp = "all"
dataset = "justus27/test-vcu"

[sampling_params]
temperature = 0.7
top_p = 0.95
max_tokens = 100
presence_penalty = 0.1
frequency_penalty = 0.1
