name_model = "Qwen/QwQ-32B"
batch_size = 4
tp = "auto"
max_model_len = 24_000

[sampling]
n = 16

[len_reward]
reward_type = "exact"
length_prompt_location = "instruction"

[len_reward.target_lengths]
a100_pcie = [4000]
a100_sxm = [4000, 8000]
h100_pcie = [4000, 8000, 14000]
h100_sxm = [8000, 14000, 20000]

[difficulty_filtering]
solve_rate_field = "solve_rate_qwen_r1_distill_7b"
min_solve_rate = 0.0
max_solve_rate = 0.7