model_name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
dataset = "PrimeIntellect/INTELLECT-2-only-math"

batch_size = 180
dp = 6
max_model_len = 16384
clean_output_path = true
rollout_path = "outputs"
output_path = "data_rollout"

[sampling]
temperature = 1.0
n = 16

[difficulty_filtering]
solve_rate_field = "solve_rate_qwen_r1_distill_7b"
min_solve_rate = 0.6
max_solve_rate = 1.0