max_steps = 660
batch_size = 1024
micro_batch_size = 1
seq_len = 16384
rollouts_per_example = 16
mask_truncated_completions = false

[sampling]
temperature = 0.8

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-7B"

[monitor.wandb]

[environment]
id = "deepcoder"

[monitor.wandb.log_extras]
interval = 50

[eval]
interval = 50
environment_ids = ["math500", "aime2024", "aime2025"]
rollouts_per_example = [1, 32, 32]

[ckpt]
interval = 100