enable_lora = true
max_loras = 32
max_cpu_loras = 32
max_lora_rank = 16
gpu_memory_utilization = 0.8

[model]
name = "Qwen/Qwen3-0.6B-Base"
max_model_len = 4096

[server]
port = 8000

[vllm_extra]
max_num_seqs = 384
max_num_batched_tokens = 32768
