name: rl
enable_pane_titles: true

on_project_start: rm logs/trainer.log && rm logs/orchestrator.log

windows:
  - Entrypoint:
      panes:
        - RL: echo "Run your RL entrypoint here"
  - Training:
      layout: even-horizontal
      panes:
        - Orchestrator:
          - |
            while true; do
              echo "Waiting for orchestrator log file..."
              while [ ! -f logs/orchestrator.log ]; do sleep 1; done
              echo "Following orchestrator.log..."
              tail -F logs/orchestrator.log
            done
        - Trainer:
          - |
            while true; do
              echo "Waiting for trainer log file..."
              while [ ! -f logs/trainer.log ]; do sleep 1; done
              echo "Following trainer.log..."
              tail -F logs/trainer.log
            done
  - Monitor:
      layout: even-horizontal
      panes:
        - GPU: nvtop
        - CPU: htop
            