name: RL
enable_pane_titles: true
windows:
  - RL:
      layout: even-horizontal
      panes:
        - Training: 
          - export CUDA_VISIBLE_DEVICES=0 
          - clear
          - uv run torchrun src/zeroband/train.py @ configs/training/simple_reverse_two_gpu.toml --monitor.file.path train-monitor.jsonl
        - Inference:
          - export CUDA_VISIBLE_DEVICES=1 
          - clear
          - uv run src/zeroband/infer.py @ configs/inference/simple_reverse_two_gpus.toml --monitor.file.path infer-monitor.jsonl --monitor.wandb.prefix infer
  - Monitor:
      layout: even-horizontal
      panes:
        - Training Logs: watch -n 1 "cat train-monitor.jsonl | tail -n 10"
        - Inference Logs: watch -n 1 "cat infer-monitor.jsonl | tail -n 10"
  - System:
      layout: even-horizontal
      panes:
        - CPU Monitor: htop
        - GPU Monitor: nvtop