max_steps = 50
seq_len = 2048

[deployment]
num_infer_gpus = 4
num_train_gpus = 4
gpus_per_node = 8

[model]
name = "JJJYmmm/ZAYA1-8B-HF"

[wandb]
project = "prime-takehome"

[orchestrator]
batch_size = 128
rollouts_per_example = 16

[orchestrator.train.sampling]
max_completion_tokens = 128

[orchestrator.train.sampling.extra_body.chat_template_kwargs]
enable_thinking = false

[[orchestrator.train.env]]
id = "reverse-text"

[trainer.optim]
lr = 3e-6

[trainer.model]
impl = "custom"
attn = "flash_attention_2"
optim_cpu_offload = true

[trainer.model.ac]
freq = 1

[ckpt]

[inference]

[inference.model]
name = "Zyphra/ZAYA1-8B"
