environment_ids = ["math500", "aime2024"]
rollouts_per_example = 1

[env.math500]
use_think = true

[env.aime2024]
rollouts_per_example = 16
use_think = true

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"