[project]
name = "vf-pydantic-adherence"
version = "0.1.1"
tags = ["json", "structure", "single-turn", "pydantic", "parsing"]
license = "Apache-2.0"
description = "Single-turn JSON-structured output validated against per-sample Pydantic models."
dependencies = [
    "verifiers>=0.1.2",
    "datasets",
    "pydantic",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["vf_pydantic_adherence.py"]
