[project]
name = "prime-rl-vllm-env"
version = "0.0.0"
description = "Isolated vLLM environment for prime-rl"
requires-python = "~=3.12.0"
dependencies = [
    "torch==2.7.1+cu128",
    "vllm==0.10.1.1",
]

[tool.uv]
prerelease = "allow"

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/test/cu128"
explicit = true

