[project]
name = "vf-ascii-tree"
version = "0.1.4"
tags = ["formatting", "ascii", "single-turn", "xml", "synthetic"]
license = "Apache-2.0"
description = "Single-turn evaluation where the model generates ASCII tree diagrams from prompts."
dependencies = [
    "verifiers>=0.1.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["vf_ascii_tree.py"]
