output_dir = "/beegfs/mika/nemotron-nano-base-infer"
gpu_memory_utilization = 0.8

[slurm]
job_name = "nemotron-nano-base"

[deployment]
type = "single_node"

[model]
name = "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-Base-BF16"
trust_remote_code = true
tool_call_parser = "qwen3_coder"

[parallel]
tp = 8
