max_steps = 100
seq_len = 16384

[wandb]
project = "general-agent-debug"
name = "qwen3-4b-v1"

[model]
name = "Qwen/Qwen3-4B-Instruct-2507"

[trainer]

[trainer.model.ac]
freq = 1

[orchestrator]
batch_size = 16
group_size = 4

[orchestrator.train.sampling]
max_completion_tokens = 4096

[[orchestrator.train.env]]
id = "general-agent"

[inference]
gpu_memory_utilization = 0.85

[inference.model]
max_model_len = 16384

[inference.parallel]
dp = 1
