max_batch_size = 360
clean_rollout_path = true
rollout_path = "data_rollout"

[model]
name = "justus27/qwen-4b-mini-sft"
max_model_len = 8192

[data]
name = "PrimeIntellect/Skywork-OR1-RL-Data-v1-math-prime-rl-format"
difficulty_filtering = { solve_rate_field = "solve_rate_qwen_r1_distill_1b", min_solve_rate = 0.1, max_solve_rate = 0.7 }

[parallel]
dp = 6
tp = 1

[sampling]
temperature = 1.0
n = 32