name_model = "debugmodel"
max_samples = 32
batch_size = 8
dataset = "justus27/test-vcu"

[sampling_params]
temperature = 0.7
top_p = 0.95
max_tokens = 100
presence_penalty = 0.1
frequency_penalty = 0.1
logprobs = None
