model_name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
dataset = "PrimeIntellect/INTELLECT-2-RL-Dataset"

batch_size = 44
dp = 6
max_model_len = 8000
clean_output_path = true

[difficulty_filtering]
solve_rate_field = "solve_rate_qwen_r1_distill_7b"
min_solve_rate = 0.6
max_solve_rate = 0.9