clean_rollout_path = false
max_batch_size = 512


[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"
max_model_len = 2048

[data]
name = "justus27/math-hendrycks-genesys-format"

[parallel]
tp = 8
dp = 1

[rl]
ckpt_path = "checkpoints"
clean_ckpt_path = true