model_name = "willcb/Qwen2.5-0.5B-Reverse-SFT"
dataset = "PrimeIntellect/reverse_text_dataset_debug"
batch_size = 16
dp = 1
rollout_path = "outputs"
output_path = "data_rollout"
max_model_len = 2048
clean_output_path = true