max_steps = 1000
seq_len = 8192
batch_size = 1024
micro_batch_size = 1
rollouts_per_example = 16

[model]
name = "PrimeIntellect/Qwen3-0.6B"

[environment]
id = "math-python"

[environment.args]
max_concurrent_sandboxes = 64
use_think = true
max_turns = -1