max_steps = 300
seq_len = 16384
batch_size = 1024
micro_batch_size = 1
rollouts_per_example = 16

[model]
name = "PrimeIntellect/Qwen3-8B"

[environment]
id = "math-python"

[environment.args]
max_turns = 10

[sampling]
max_tokens = 16384