max_steps = 200

[wandb]
project = "multiagent"
name = "ultimatum-game-lora"

[model]
name = "Qwen/Qwen3-4B-Instruct-2507"

[orchestrator]
batch_size = 128
rollouts_per_example = 16

[orchestrator.sampling]
max_tokens = 32
temperature = 1.0

[orchestrator.wandb.log_extras]
samples = true
interval = 10

[[orchestrator.env]]
id = "ultimatum-game-shared"
name = "ultimatum_game_shared"

[trainer]

[trainer.model.lora]
rank = 32

[inference]
enable_lora = true

[inference.server]
max_model_len = 2048
