max_steps = 400
seq_len = 4096

[wandb]
project = "multiagent"
name = "ultimatum-game-lora"

[model]
name = "Qwen/Qwen3-1.7B"

[orchestrator]
batch_size = 128
rollouts_per_example = 16

[orchestrator.sampling]
max_tokens = 32
temperature = 1.0

[orchestrator.wandb.log_extras]
samples = true
interval = 10

[[orchestrator.env]]
id = "ultimatum-game"
name = "ultimatum_game"

[orchestrator.multi_agent_lora.actors]
proposer = "run_proposer"
responder = "run_responder"

[trainer]
max_concurrent_runs = 2

[trainer.model.lora]
rank = 32

[inference]
enable_lora = true
