## to run on 8H100
batch_size = 512
micro_batch_size = 2
rollouts_per_prompt = 16
seq_len = 2048
mask_truncated_completions = false

[model]
name = "Qwen/Qwen3-30B-A3B"

[monitor.wandb]

[environment]
id = "vf-hendrycks-math"

[monitor.wandb.log_extras]
interval = 10

[eval]
interval = 50
benchmarks = ["math500", "aime24", "aime25"]
rollouts_per_prompt = [1, 16, 16]
