max_steps = 500
batch_size = 1024
micro_batch_size = 1
rollouts_per_example = 16
seq_len = 16384
mask_truncated_completions = false

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-1.5B"

[sampling]
max_tokens = 16384

[environment]
id = "hendrycks-math"