max_steps = 500
batch_size = 512
micro_batch_size = 4
rollouts_per_example = 16
seq_len = 4096
mask_truncated_completions = false

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-1.5B"

[sampling]
max_tokens = 4096

[environment]
id = "hendrycks-math"