max_steps = 100
batch_size = 1024
rollouts_per_example = 16
seq_len = 16384

[buffer]
seed = 0

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-1.5B"

[sampling]
max_tokens = 16384
seed = 0

[environment]
id = "hendrycks-math"