batch_size = 128
rollouts_per_example = 16
seq_len = 2048
max_steps = 20
mask_truncated_completions = false

[model]
name = "PrimeIntellect/Qwen3-0.6B-Reverse-Text-SFT"

[sampling]
max_tokens = 128

[environment]
id = "reverse-text"
