name_model = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
batch_size = 14
dp = 6
rollout_path = "outputs"
output_path = "data_rollout"
max_model_len = 2048
dataset = "justus27/math-hendrycks-genesys-format"



[sampling]
temperature = 0.6
top_k = 40
min_p = 0.1
top_p = 0.95



class SamplingParamConfig(BaseConfig):
    temperature: float = 0.6
    max_tokens: int | None = None
    ignore_eos: bool = False
    top_p: float = 1
    n: int = 8
    logprobs: int = 0  # 0 mean 1 logprob here
    top_k: int = -1
