name_model = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
batch_size = 22
dp = 6
rollout_path = "outputs"
output_path = "data_rollout"

max_model_len = 4200


[sampling]
n = 16

[len_reward]
reward_type = "exact"
length_prompt_location = "instruction"
target_lengths = [1000, 2000, 3000, 4000]

[difficulty_filtering]
solve_rate_field = "solve_rate_qwen_r1_distill_7b"
min_solve_rate = 0.1
max_solve_rate = 0.8