## to run on 8H200
batch_size = 512
micro_batch_size = 8
rollouts_per_prompt = 16
seq_len = 2048
mask_truncated_completions = false

[model]
name = "willcb/Qwen3-30B-A3B"

[monitor.wandb]

[environment]
id = "hendrycks-math"

[monitor.wandb.log_samples]
interval = 10

[eval]
interval = 50
benchmarks = ["math500", "aime24", "aime25"]
