## to run on H100
batch_size = 512
micro_batch_size = 2
rollouts_per_prompt = 16
seq_len = 2048
mask_truncated_completions = false

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-7B"

[monitor.wandb]

[environment]
id = "hendrycks-math"

[monitor.wandb.log_extras]
interval = 10

[eval]
interval = 50
benchmarks = ["math500", "aime24", "aime25"]
rollouts_per_prompt = [1, 16, 16]

[ckpt]
interval = 200 