rollout_path = "/data"
toploc = true

[model]
name = "deepseek-ai/DeepSeek-R1-0528"
max_model_len = 32768

[parallel]
tp = "auto"

[monitor.socket]
enable = true

[parallel.pp]
connection_num_retries = 100

[sampling]
n = 8
temperature = 0.6
top_p = 0.95