rollout_path = "/data"
toploc = true

[model]
name = "Qwen/Qwen3-4B"
max_model_len = 16384

[parallel]
tp = "auto"

[monitor.socket]
enable = true

[parallel.pp]
connection_num_retries = 100

[sampling]
n = 8
temperature = 0.6
top_p = 0.95
top_k = 20