recompute_logprobs = false

[monitor.wandb]
project = "prime-rl-moe-debug" # TODO: Remove before merging

[model]
name = "moonshotai/Moonlight-16B-A3B"
ac = true
trust_remote_code = true

[optim]
lr = 1e-6 
