batch_size = 512
micro_batch_size = 4
rollouts_per_example = 8
seq_len = 2048
max_steps = 100
mask_truncated_completions = false

[model]
name = "Qwen/Qwen3-30B-A3B-Instruct-2507"

[sampling]
max_tokens = 768

[environment]
id = "wiki-search"