name_model = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
project = "rl-Qwen1.5B"

[train]
micro_bs = 8
reshard_after_forward = true
attn_impl = "flash_attention_2"

[optim]
batch_size = 512
warmup_steps = 1
total_steps = 100000000000000
step_per_rollout = 4

[optim.optim]
lr = 1e-6



[data]
path = "data_rollout"
seq_length = 2048