name_model = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
project = "rl-Qwen1.5B"

[train]
micro_bs = 32
reshard_after_forward = true

[optim]
batch_size = 128
warmup_steps = 1
total_steps = 100000000000000
step_per_rollout = 8

[optim.optim]
lr = 1e-6
