max_steps = 12

[data.fake]
batch_size = 32

[model]
name = "Qwen/Qwen3.5-9B"
seq_len = 16384
optim_cpu_offload = false
fsdp_cpu_offload = false

[model.vlm]
vision_encoder_attr = "model.visual"
language_model_attr = "model.language_model"
