# Example evaluation configuration with Prime Hub integration
# This shows how to automatically push evaluation results to Prime Hub

environment_ids = ["reverse-text"]
rollouts_per_example = 8
num_examples = 100

# Enable pushing evaluation results to Prime Hub
# Requires prime-cli to be installed and configured with API credentials
# Install: pip install prime-cli
# Configure: prime config set-api-key YOUR_API_KEY
# When enabled, displays the evals viewer URL after each push
push_to_env_hub = true

# Optional: Save to disk (default: true)
save_to_disk = true

# Optional: Save to HuggingFace Hub
# save_to_hf = "your-org/eval-results"

[model]
name = "PrimeIntellect/Qwen3-0.6B-Reverse-Text-SFT"

[sampling]
temperature = 0.7
max_tokens = 128

