model_name = "Qwen/Qwen3-0.6B"
wandb = false
collate_mode = "padding"

[grpo]
kl_coef = 0.02

[train]
micro_bs = 1

[optim]
batch_size = 2
warmup_steps = 10
total_steps = 2

[data]
fake = true
seq_length = 128
timeout = 1