model_name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
project = "math-ablation"

collate_mode = "packing"

[train]
micro_bs = 1 # change to 8 for H200
reshard_after_forward = true

[data]
seq_length = 8192
path = "data_rollout"

[optim]
warmup_steps = 1
batch_size = 2048
total_steps = 10000000000000000000
step_per_rollout = 1


[optim.optim]
lr = 1e-6

[ckpt]
rollout_path = "outputs"
clean_rollout_path = true