name_model = "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"
project = "qwen_32_rl"

[train]
micro_bs = 32
reshard_after_forward = true

[optim]
batch_size = 1024
warmup_steps = 1000
total_steps = 8192

[optim.optim]
lr = 7e-4
