name_model = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
project = "qwen_7B_rl"

[train]
micro_bs = 1
ac_ckpt = true

[optim]
batch_size = 128
warmup_steps = 1000
total_steps = 8192

[data]
seq_length = 8192

[optim.optim]
lr = 7e-4
