max_steps = 30

[monitor.wandb]
project = "reverse-text-debug"
group = "reverse-text-debug"

[model]
name = "willcb/Qwen2.5-0.5B-Reverse-SFT"

[optim]
lr = 3e-6

### Orchestrator ###

[orchestrator]
batch_size = 128
micro_batch_size = 16
rollouts_per_prompt = 16
seq_len = 128
max_steps = 30
mask_truncated_completions = false

[orchestrator.model]
name = "willcb/Qwen2.5-0.5B-Reverse-SFT"

[orchestrator.environment]
id = "reverse-text"

[orchestrator.sampling]
max_tokens = 128