max_steps = 30

[model]
name = "willcb/Qwen2.5-0.5B-Reverse-SFT"
ac = true

[optim]
lr = 3e-6

### Orchestrator ###

[orchestrator]
batch_size = 64
micro_batch_size = 8
seq_len = 1024
max_steps = 30

[orchestrator.model]
name = "willcb/Qwen2.5-0.5B-Reverse-SFT"

[orchestrator.environment]
id = "reverse-text"

[orchestrator.sampling]
n = 8
max_seq_len = 256