max_steps = 20

[model]
name = "willcb/Qwen2.5-0.5B-Reverse-SFT"

[optim]
lr = 3e-6

[monitor.wandb]
project = "reverse-text"

[orchestrator]
batch_size = 128
micro_batch_size = 128
seq_len = 128

[orchestrator.data]
name = "mikasenghaas/reverse_text_dataset_debug_50_seq_len"

[orchestrator.sampling]
n = 16