[monitor.wandb]
project = "math-debug"

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"

[train]
micro_bs = 4
reshard_after_forward = true
ac_ckpt = true
torch_compile = true

[optim]
batch_size = 1024
step_per_rollout = 1

[optim.optim]
lr = 1e-6


[data]
path = "rollouts"
seq_length = 4096

[ckpt]
rollout_path = "checkpoints"
clean_rollout_path = true
async_save = true