stop_after_steps = 50

[monitor.wandb]
project = "reverse-debug"

[model]
name = "willcb/Qwen2.5-0.5B-Reverse-SFT"

[train]
micro_bs = 32
reshard_after_forward = true

[optim]
batch_size = 64

[optim.optim]
lr = 3e-6

[data]
path = "rollouts"
seq_length = 128

[ckpt]
rollout_path = "checkpoints"
clean_rollout_path = true