max_steps = 20
seq_len = 2048

[model]
name = "PrimeIntellect/Qwen3-0.6B-Reverse-Text-SFT"

[wandb]
project = "reverse-text-debug"
name = "debug-opd"

[deployment]
num_teacher_gpus = 1

[orchestrator]
training_mode = "opd"
batch_size = 128
rollouts_per_example = 16

[orchestrator.train.sampling]
max_completion_tokens = 128

[[orchestrator.train.env]]
id = "reverse-text"

[orchestrator.eval]
interval = 1
num_examples = 128

[orchestrator.eval.sampling]
max_completion_tokens = 128

[[orchestrator.eval.env]]
id = "reverse-text"

[orchestrator.teacher]

[trainer.optim]
lr = 3e-6

[trainer.loss]
teacher_tau = 0.5

[ckpt]

[inference]
