name_model = "PrimeIntellect/llama-1b-fresh"
project = "debug_1B_zero_band"

[train]
micro_bs = 32
reshard_after_forward = true

[optim]
batch_size = 1024
warmup_steps = 1000
total_steps = 8192

[optim.optim]
lr = 7e-4
