total_steps = 3
batch_size = 32


[train]
name_model = "debugmodel"
wandb = false

[train.data]
fake = false
timeout = 1000000000000000000000000
num_workers = 1
seq_length = 1024

[train.train]
micro_bs = 8

[train.optim]
warmup_steps = 10
step_per_rollout = 2

[inference]
name_model = "debugmodel"
max_samples = 100000
max_seq_len = 1024
enforce_eager = true