total_steps = 1000


[train]
name_model = "debugmodel"
wandb = false

[train.data]
fake = true
timeout = 1

[train.train]
micro_bs = 8

[train.optim]
batch_size = 16
warmup_steps = 10
total_steps = 100000

[inference]
name_model = "debugmodel"
max_samples = 100000
batch_size = 8
sample_per_file = 32
dataset = "justus27/test-vcu"

