total_steps = 2000
batch_size = 1024           


[train]
name_model = "Qwen1.5B"
project = "rl-Qwen1.5B"

[train.train]
micro_bs = 32
reshard_after_forward = true

[train.optim]
warmup_steps = 1
step_per_rollout = 8

[train.data]
timeout = 3600


[train.optim.optim]
lr = 1e-6


[inference]
name_model = "Qwen1.5B"

[inference.sampling]
max_tokens = 16_000