total_steps = 2000
batch_size = 1024


[train]
name_model = "Qwen1.5B"
project = "rl-Qwen1.5B"

[train.train]
micro_bs = 32
reshard_after_forward = true

[train.optim]
warmup_steps = 1
batch_size = 128
step_per_rollout = 8

[train.optim.optim]
lr = 1e-6

[inference]
batch_size = 128

[inference.sampling]
n = 8
