# Supports:
# - https://huggingface.co/deepseek-ai/DeepSeek-R1-0528
# - https://huggingface.co/deepseek-ai/DeepSeek-R1-0528-Qwen3-8B

[model]
max_model_len = 65536

[sampling]
temperature = 0.6
top_p = 0.95
n = 64