# Supports:
# - https://huggingface.co/deepseek-ai/DeepSeek-R1
# - https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
# - https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
# - https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-8B
# - https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
# - https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
# - https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-70B

[model]
max_model_len = 32768

[sampling]
temperature = 0.6
top_p = 0.95
n = 64