batch_size = 128
max_steps = 50

[model]
name = "willcb/Qwen2.5-0.5B-Reverse-SFT"

[data]
name = "mikasenghaas/reverse_text_dataset_debug_50_seq_len"

[sampling]
n = 16

[train]
batch_size = 128
micro_bs = 16
max_seq_len = 128
n_data_ranks = 1
