batch_size = 128
micro_batch_size = 64
seq_len = 128
max_steps = 50

[model]
name = "willcb/Qwen2.5-0.5B-Reverse-SFT"

[data]
name = "mikasenghaas/reverse_text_dataset_debug_50_seq_len"

[sampling]
n = 16