max_steps = 20

[env_vars]
TRITON_CACHE_DIR = "/tmp/garrett/.triton-cache"
UV_NO_SYNC = "1"

[model]
name = "/home/huggingface/hub/models--zai-org--GLM-4.5-Air/snapshots/a24ceef6ce4f3536971efe9b778bdaa1bab18daa"
attn = "flash_attention_3"
optim_cpu_offload = false
fsdp_cpu_offload = false
ac_offloading = "None"

[model.ac]
mode = "full"
freq = 1

[model.debug]
num_layers = 24

[optim]
lr = 1e-5

[renderer]
name = "glm-4.5"

[data]
type = "sft"
name = "PrimeIntellect/INTELLECT-3-SFT-10K"
splits = ["math"]
seed = 0
batch_size = 16
micro_batch_size = 1
seq_len = 16384

[monitors.wandb]
entity = "primeintellect"
project = "perf-router-rs-buffer-cap"

[deployment]
type = "multi_node"
num_train_nodes = 2

[slurm]
job_name = "rs-cap-ab"
partition = "all"
time = "01:00:00"
