model_name = "mikasenghaas/Qwen3-8B-1.2"
dataset = "justus27/rl-code-and-math"
max_samples = 32
batch_size = 8
enforce_eager = true
toploc = true
seed = 0

[sampling]
max_tokens = 16

[pp]
rank = 1
world_size = 2
iroh_seed = 1
iroh_peer_id = "ee1aa49a4459dfe813a3cf6eb882041230c7b2558469de81f87c9bf23bf10a03"