model_name = "mikasenghaas/Qwen3-8B-0.2"
dataset = "justus27/rl-code-and-math"
max_samples = 32
batch_size = 8
enforce_eager = true
toploc = true
seed = 0

[sampling]
max_tokens = 16

[pp]
rank = 0
world_size = 2
iroh_seed = 0
iroh_peer_id = "ff87a0b0a3c7c0ce827e9cada5ff79e75a44a0633bfcb5b50f99307ddb26b337"