name: Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  cpu-tests:
    name: Run CPU Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync
      - name: Run CPU tests
        run: uv run pytest tests -m "not gpu"

  gpu-tests:
    name: Run GPU Tests
    runs-on: self-hosted
    timeout-minutes: 20
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync && uv sync --extra fa
      - name: Run GPU tests
        run: uv run pytest tests -m "gpu and not e2e"

  e2e-tests:
    name: Run E2E Tests
    runs-on: self-hosted
    timeout-minutes: 20
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync && uv sync --extra fa
      - name: Run E2E tests
        env:
          USERNAME_CI: CI_RUNNER
        run: uv run pytest -s tests -m "e2e"

