max_steps = 1
dashboard = false

[model]
name = "Qwen/Qwen3.5-9B"
impl = "custom"
optim_cpu_offload = false
ac_offloading = "None"

[model.debug]
random_init = true

[model.compile]
fullgraph = true

[data]
type = "fake"
batch_size = 8
micro_batch_size = 1
seq_len = 128
length = "fixed"

[deployment]
type = "single_node"
gpus_per_node = 8
num_train_gpus = 8

[slurm]
job_name = "qwen3-5-9b-fullgraph"
partition = "all"
time = "00:45:00"
