[project]
name = "vf-acereason-math"
version = "0.1.1"
tags = ["math", "single-turn", "think", "boxed-answer"]
license = "Apache-2.0"
description = "Single-turn math word problems from AceReason-Math with boxed numeric answers and CoT."
dependencies = [
    "verifiers>=0.1.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["vf_acereason_math.py"]
